### ISSUE TITLE
Composite.Community.Blog.Latest gives an error on  pages with Path Info

### ISSUE THREAD

**Issue by Deltaworks** [Orckestra/CMS-Packages#48] opened 2016-12-16 04:46 UTC
I've placed the Blog.Latest function in the footer of my page.
On normal pages it works great, but when I go to the detail of for instance my porfolio page, I get the following error:

Error: Value cannot be null. Parameter name: source
11: }
12: @{
13:     var entries = BlogFacade.GetEntries(true).Take(5);
14: }
15: 
Function: Composite.Community.Blog.Latest

**Comment by mawtex** [comment] 2016-12-16 13:56
Looks like a bug in the blog package - you can pull the code from https://github.com/Orckestra/CMS-Packages/tree/master/Composite.Community.Blog - if you can't fix it, please put the bug there. If you can fix it, please send a pull request :)

My guess the error is in BlogFacade.cs - specifically the method here:

        public static Expression<Func<Entries, bool>> GetBlogFilterFromUrl(bool isGlobal)
        {
            Guid currentPageId = isGlobal ? Guid.Empty : PageRenderer.CurrentPageId;
            string[] pathInfoParts = GetPathInfoParts();

            return GetBlogFilter(currentPageId, pathInfoParts);
        }

Likely the fix here is to ensure pathInfoParts is set to null if isGlobal is true, like

            string[] pathInfoParts = isGlobal  ? null : GetPathInfoParts();

**Comment by Deltaworks** [comment] 2016-12-16 14:14
Hi Mawtex, 

Thanks for your quick reply.
I'm running the latest version of the blog v2.3.5.
I don't see the BlogFacade.cs file on my web server. So I don't know how to chance/edit it.

I'm a little new to Asp.net so I don't really understand the whole github etc.

**Comment by InnaBoitsun** [comment] 2016-12-19 12:41
Hello,

The bug was reproduced and will be fixed.
You can apply a quick fix with next steps:
1) Locate the razor function "Composite.Community.Blog.Latest" (~\App_Data\Razor\Composite\Community\Blog\Latest.cshtml) 
2) Edit the function and replace line 13:
`var entries = BlogFacade.GetEntries(true).Take(Count);`
with next:
`var entries = Data.Get<Entries>().OrderByDescending(e => e.Date).Take(Count);`

**Comment by Deltaworks** [comment] 2016-12-19 13:06
Hi Inna,

Thanks for the quick fix.
It works like a charm.

Regards,

Alex


Deltaworks N.V.
Kaya Roi Katochi 34
Willemstad, Curacao
Netherlands Antilles
phone: +5999-7368540
mobile: +5999-5229716
info@deltaworksinc.com
http://www.deltaworksinc.com

**Closed** 2017-02-16 10:48 UTC
Labels: bug
